In [ ]:
from Audio import Audio
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [ ]:
prova = Audio("/mnt/f/PhD/_Segments/44kHz/15s/pan_audio_160224_ult1_group5_0011.wav", 44100)
signal_au, sr = prova.load(normalize=False)
plt.plot(signal_au)

In [ ]:
np.max(signal_au)

In [ ]:
import noisereduce as nr

noise = nr.reduce_noise(signal_au, 44100, stationary=True, n_std_thresh_stationary=1.5, prop_decrease=0.95)

In [ ]:
plt.plot(noise)

In [ ]:
from scipy.io.wavfile import write
write("/mnt/c/Users/nicor/Desktop/prova.wav", 44100, noise)

In [ ]:
from pyAudioAnalysis import ShortTermFeatures, MidTermFeatures

mid, short, mid_names = MidTermFeatures.mid_feature_extraction(noise, 44100, 5.0*44100, 1.0*44100, 0.050*44100, 0.025*44100)

In [ ]:
import pandas as pd

df = pd.DataFrame(mid.transpose(), columns=mid_names)
df

In [ ]:
from pyAudioAnalysis import audioBasicIO

[sig, x] = audioBasicIO.read_audio_file("/mnt/f/PhD/_Segments/44kHz/15s/pan_audio_160224_ult1_group5_0011.wav")
x

In [ ]:
from pyAudioAnalysis import ShortTermFeatures, MidTermFeatures

short, short_names = ShortTermFeatures.feature_extraction(noise, 44100, 0.050*44100, 0.025*44100)
df = pd.DataFrame(short.transpose(), columns=short_names)
df

In [ ]:
mid, short, mid_names = MidTermFeatures.mid_feature_extraction(noise, 44100, 5.0*44100, 5.0*44100, 0.050*44100, 0.025*44100)
df = pd.DataFrame(mid.transpose(), columns=mid_names)
df

In [ ]:
mid_names

In [1]:
from pyAudioAnalysis import ShortTermFeatures, MidTermFeatures



In [1]:
from pyAudioAnalysis import audioBasicIO
import pandas as pd

sig, x = audioBasicIO.read_audio_file("/mnt/f/PhD/_Segments/44kHz/15s/pan_audio_160224_ult1_group5_0011.wav")
x

array([-3073, -2924, -2593, ...,  -518,  -718,  -862], dtype=int16)

In [3]:
short, short_names = ShortTermFeatures.feature_extraction(x, 44100, 0.050*44100, 0.025*44100)
df = pd.DataFrame(short.transpose(), columns=short_names)
df

zcr    energy  energy_entropy  spectral_centroid  spectral_spread  \
0    0.037205  0.005057        3.103166           0.102955         0.149642   
1    0.036751  0.004893        3.096962           0.113393         0.166708   
2    0.034936  0.004864        3.171716           0.119540         0.180751   
3    0.039927  0.003130        3.115421           0.117547         0.170023   
4    0.037205  0.001799        3.195863           0.109788         0.153874   
..        ...       ...             ...                ...              ...   
593  0.030853  0.009170        3.175021           0.117404         0.152220   
594  0.030853  0.008841        3.211104           0.122837         0.180919   
595  0.028584  0.007261        3.113219           0.105927         0.167608   
596  0.018149  0.003806        3.012864           0.088289         0.132422   
597  0.025862  0.002082        3.053213           0.120421         0.190058   

     spectral_entropy  spectral_flux  spectral_rolloff     mfcc_1    mfcc_2  \
0            0.183496       0.000000          0.048094 -24.477476  2.402611   
1            0.210427       0.002796          0.043557 -24.706539  2.509733   
2            0.205513       0.002478          0.043557 -24.993319  2.623126   
3            0.218112       0.003811          0.049002 -25.520228  2.299821   
4            0.239267       0.005125          0.056261 -26.056741  2.127934   
..                ...            ...               ...        ...       ...   
593          0.221669       0.004382          0.024501 -25.086587  2.532998   
594          0.143338       0.002658          0.024501 -25.176000  2.693414   
595          0.111478       0.003716          0.024501 -25.443259  2.910688   
596          0.106013       0.005606          0.024501 -26.366578  2.991781   
597          0.128603       0.004755          0.024501 -26.693709  2.894973   

     ...  delta chroma_4  delta chroma_5  delta chroma_6  delta chroma_7  \
0    ...        0.000000        0.000000        0.000000        0.000000   
1    ...        0.009621       -0.009775        0.001235        0.006662   
2    ...        0.014956       -0.025845        0.003177        0.017679   
3    ...       -0.004153       -0.006618       -0.001057       -0.022017   
4    ...       -0.013431       -0.003668       -0.005066        0.032868   
..   ...             ...             ...             ...             ...   
593  ...       -0.036040       -0.062763        0.000234        0.016626   
594  ...        0.008028        0.023917       -0.004061       -0.013095   
595  ...       -0.070043        0.020933       -0.001114        0.004467   
596  ...       -0.018832       -0.034621        0.007550        0.009732   
597  ...       -0.006111       -0.019526       -0.005084        0.035446   

     delta chroma_8  delta chroma_9  delta chroma_10  delta chroma_11  \
0          0.000000        0.000000         0.000000         0.000000   
1          0.001991        0.017996         0.007763        -0.021455   
2          0.001949       -0.019775        -0.023233         0.000795   
3         -0.003499       -0.004164         0.018054         0.049684   
4         -0.000490        0.004234        -0.026451        -0.016587   
..              ...             ...              ...              ...   
593        0.000899       -0.000220         0.009138         0.002882   
594       -0.000749        0.000493        -0.007907        -0.002319   
595       -0.000642        0.000063         0.015427         0.028177   
596        0.000111       -0.000025         0.080893        -0.018696   
597        0.001974        0.003454        -0.046236         0.018770   

     delta chroma_12  delta chroma_std  
0           0.000000          0.000000  
1           0.000342         -0.001512  
2          -0.000224         -0.000501  
3           0.000494          0.004997  
4           0.000654         -0.003214  
..               ...               ...  
593        -0.001647         -0.009

In [4]:
mid, short, mid_names = MidTermFeatures.mid_feature_extraction(x, 44100, 5.0*44100, 5.0*44100, 0.050*44100, 0.025*44100)
df = pd.DataFrame(mid.transpose(), columns=mid_names)
df

zcr_mean energy_mean energy_entropy_mean spectral_centroid_mean  \
0  0.063968    0.004591            3.163498               0.132331   
1  0.052666    0.001623            3.189023               0.125297   
2  0.045235    0.012054            3.165104               0.109706   

  spectral_spread_mean spectral_entropy_mean spectral_flux_mean  \
0             0.162972               0.47525           0.002684   
1             0.169571              0.290566           0.003472   
2             0.155222              0.235214           0.004216   

  spectral_rolloff_mean mfcc_1_mean mfcc_2_mean  ... delta chroma_4_kurtosis  \
0                0.0954  -26.163431    1.658127  ...                4.641774   
1              0.065099  -27.726184    2.122959  ...                5.342299   
2              0.060533  -25.859031    2.368291  ...                6.946889   

  delta chroma_5_kurtosis delta chroma_6_kurtosis delta chroma_7_kurtosis  \
0                3.644048                4.554538                2.180166   
1                8.309539               10.318567                1.524412   
2                7.834902                5.541253                1.071198   

  delta chroma_8_kurtosis delta chroma_9_kurtosis delta chroma_10_kurtosis  \
0                5.819222                2.854223                 2.923262   
1                9.917951               34.599845                 7.359853   
2                15.13779                3.053349                 2.729062   

  delta chroma_11_kurtosis delta chroma_12_kurtosis delta chroma_std_kurtosis  
0                 2.981489                28.500135                  1.168233  
1                13.674627                 4.398547                  0.088872  
2                 2.993538                17.431909                    0.3235  

[3 rows x 340 columns]

In [5]:
from Features import Feature

feat = Feature(low_lvl_wnd=0.05,low_lvl_step=0.025,mid_lvl_wnd=5.0,mid_lvl_step=5.0)
feat.ms

/home/nicorb/miniconda3/envs/audio-analysis/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


5.0

In [6]:
l, m = feat(x, 44100)
m

zcr_mean energy_mean energy_entropy_mean spectral_centroid_mean  \
0  0.063968    0.004591            3.163498               0.132331   
1  0.052666    0.001623            3.189023               0.125297   
2  0.045235    0.012054            3.165104               0.109706   

  spectral_spread_mean spectral_entropy_mean spectral_flux_mean  \
0             0.162972               0.47525           0.002684   
1             0.169571              0.290566           0.003472   
2             0.155222              0.235214           0.004216   

  spectral_rolloff_mean mfcc_1_mean mfcc_2_mean  ... delta chroma_4_kurtosis  \
0                0.0954  -26.163431    1.658127  ...                4.641774   
1              0.065099  -27.726184    2.122959  ...                5.342299   
2              0.060533  -25.859031    2.368291  ...                6.946889   

  delta chroma_5_kurtosis delta chroma_6_kurtosis delta chroma_7_kurtosis  \
0                3.644048                4.554538                2.180166   
1                8.309539               10.318567                1.524412   
2                7.834902                5.541253                1.071198   

  delta chroma_8_kurtosis delta chroma_9_kurtosis delta chroma_10_kurtosis  \
0                5.819222                2.854223                 2.923262   
1                9.917951               34.599845                 7.359853   
2                15.13779                3.053349                 2.729062   

  delta chroma_11_kurtosis delta chroma_12_kurtosis delta chroma_std_kurtosis  
0                 2.981489                28.500135                  1.168233  
1                13.674627                 4.398547                  0.088872  
2                 2.993538                17.431909                    0.3235  

[3 rows x 340 columns]

In [90]:
from speechbrain.pretrained import VAD

VAD = VAD.from_hparams(
    source="speechbrain/vad-crdnn-libriparty",
    savedir="/mnt/c/Users/nicor/PycharmProjects/AudioAnalysis/tmpdir"
)

In [91]:
import librosa as lb


boundaries = VAD.get_speech_segments("/mnt/e/Nicola/16kKz/15s/IB4001.Mix-Headset_026.wav", large_chunk_size=5, small_chunk_size=2, 
overlap_small_chunk=True, apply_energy_VAD=True, double_check=True, en_activation_th=0.23, en_deactivation_th=0.20, close_th=0.25, len_th=0.5)

In [92]:
boundaries

tensor([[ 0.0000,  1.5000],
        [ 1.8900, 11.0800],
        [12.3500, 14.9700]])

In [106]:
import torch

sig = torch.tensor(x)
sig = sig / (2**15)
sig

tensor([-0.0938, -0.0892, -0.0791,  ..., -0.0158, -0.0219, -0.0263])

In [107]:
bound = VAD.get_speech_prob_chunk(sig)
bound

tensor([[[0.2161],
         [0.1825],
         [0.1581],
         ...,
         [0.2264],
         [0.2256],
         [0.1901]]])

In [108]:
bound = VAD.apply_threshold(bound)
bound

tensor([[[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]]], dtype=torch.int32)

In [110]:
bound[bound != 0] == True

tensor([], dtype=torch.bool)

In [2]:
from pyannote.audio.pipelines import OverlappedSpeechDetection

pipeline = OverlappedSpeechDetection(segmentation="pyannote/segmentation")
vad = pipeline(x)

/home/nicorb/miniconda3/envs/audio-analysis/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cpu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")


AttributeError: module 'torch.jit' has no attribute '_script_if_tracing'